namespace XsdSettings
{
	public enum AttackSubType
	{
		ProjectileFirst = 0,
		ProjectileGeneric = 1,
		ProjectileShotgun = 2,
		ProjectileSniper = 3,
		ProjectilePistol = 4,
		ProjectileCombatRifle = 5,
		ProjectileSpit = 6,
		ProjectileAxe = 7,
		ProjectileHunter = 8,
		ProjectileLast = 9,
		AreaFirst = 10,
		AreaGeneric = 11,
		AreaExplosion = 12,
		AreaGrenade = 13,
		AreaFirebird = 14,
		AreaBerserk = 15,
		AreaHunter = 16,
		AreaLast = 17,
		MeleeFirst = 18,
		MeleeGeneric = 19,
		MeleeSkillBerserkPunch = 20,
		MeleeBite = 21,
		MeleePaw = 22,
		MeleeAxe = 23,
		MeleeClaw = 24,
		MeleeHunter = 25,
		MeleeLast = 26,
		DamageOverTimeFirst = 27,
		DamageOverTimeGeneric = 28,
		DamageOverTimeFire = 29,
		DamageOverTimeShock = 30,
		DamageOverTimeCorrosive = 31,
		DamageOverTimeFirebird = 32,
		DamageOverTimeLast = 33,
		ChargeFirst = 34,
		ChargeNormal = 35,
		ChargeLast = 36,
		RecoverFirst = 37,
		Recover = 38,
		RecoverLast = 39,
		SkillFirst = 40,
		SkillTurretProjectile = 41,
		SkillReflect = 42,
		SkillLast = 43
	}
}
