namespace XsdSettings
{
	public enum ELootingType
	{
		BadassBandit = 0,
		BadassBanditKiller = 1,
		BadassBanditPsycho = 2,
		BadassPsycho = 3,
		BadassVKag = 4,
		BanditBruiser = 5,
		BanditKiller = 6,
		BanditNineToes = 7,
		BanditPsycho = 8,
		BanditRaider = 9,
		BanditSuicidePsycho = 10,
		BloodWing = 11,
		CrimsonLanceDefender = 12,
		CrimsonMechaKnoxx = 13,
		GuardianWraith = 14,
		SkagAdult = 15,
		SkagAlpha = 16,
		SkagPup = 17,
		SkagSpitter = 18,
		SkagZilla = 19,
		SpiderantTalos = 20,
		SpiderantWidowmaker = 21,
		SpiderantWorker = 22,
		CashBox = 23,
		ChestTreasure = 24,
		CrateMetal = 25,
		CrateMilitary = 26,
		SkagPile = 27,
		StorageLocker = 28,
		TrashcanLootable = 29,
		SpiderantTalosHorn = 30,
		BadassCrimsonLanceDefender = 31,
		BadassGuardianWraith = 32,
		BadassSpiderantWorker = 33,
		CrystalMine = 34,
		CrimsonLanceMedic = 35,
		Rakk = 36,
		MidgetShotgunner = 37,
		BanditScout = 38,
		BanditApollyon = 39,
		CrateMetalTut = 40,
		ArchAngel = 41,
		TheInsane = 42,
		Tenacle = 43,
		TentacleLarge = 44,
		Crabworm = 45,
		CrimsonLanceInfantry = 46,
		CrimsonLanceSniper = 47
	}
}
