namespace XsdSettings
{
	public enum ScoringActionType
	{
		BasicKill = 0,
		BasicSuicide = 1,
		BasicAssist = 2,
		BonusHeadShot = 3,
		BonusCritical = 4,
		BonusMelee = 5,
		BonusKillStreak = 6,
		BonusDominating = 7,
		BonusOneShotTwoKills = 8,
		BonusFirstBlood = 9,
		BonusLastKill = 10,
		BonusRevenge = 11,
		BonusTeamWin = 12,
		BonusTurretKill = 13,
		BonusFirebirdKill = 14,
		BonusPunchKill = 15,
		BonusMarkedKill = 16,
		BonusGrenadesKill = 17,
		BonusFirstBullet = 18,
		BonusFirstScore = 19,
		BonusNaturalbornKiller = 20,
		BonusOneManArmy = 21,
		BonusOneStoneTwoBird = 22,
		BonusTripleKilling = 23,
		BonusGenocide = 24,
		BonusPayback = 25,
		BonusAvenger = 26,
		BonusBucher = 27,
		BonusBushido = 28,
		BonusShotPutter = 29,
		BonusCatapult = 30,
		BonusSharpShooter = 31,
		BonusHeadHunter = 32,
		BonusRoadtoHell = 33,
		BonusShameless = 34,
		BonusGiveAndTake = 35,
		BonusResuscitation = 36,
		BonusAssassin = 37,
		BonusArchNemesis = 38,
		BonusEagleEye = 39,
		BonusLoveShot = 40,
		BonusAirBourne = 41,
		BonusLongevity = 42,
		BonusBackStabbing = 43,
		BonusAFK = 44,
		BonusBloodlessVictory = 45
	}
}
