public enum GuildCreationResult
{
	SUCCESS = 0,
	FAILURE_ALREADY_GUILDMEMBER = 1,
	FAILURE_GUILDNAME_EXISTS = 2,
	FAILURE_GUILDNAME_PROFANITY = 3,
	FAILURE_INSUFFICIENCY_LEVEL = 4,
	FAILURE_INSUFFICIENCY_NAME = 5,
	FAILURE_INSUFFICIENCY_MONEY = 6,
	FAILURE_INVALID_ACCOUNT = 7,
	FAILURE_GUILDBANNER_PROFANITY = 8,
	FAILURE_ETC = 9
}
