public enum GuildInvitationResult
{
	SUCCESS = 0,
	FAILURE_INVALID_ACCOUNT = 1,
	FAILURE_RECURSIVE_INVITATION = 2,
	FAILURE_INSUFFICIENCY_RIGHT = 3,
	FAILURE_INSUFFICIENCY_VACANCY = 4,
	FAILURE_INSUFFICIENCY_INVITEE_LEVEL = 5,
	FAILURE_INVITEE_ALREADY_INVITED = 6,
	FAILURE_INVITEE_ALREADY_HAS_A_GUILD = 7,
	FAILURE_ETC = 8
}
